"""Restricted smoke executor for NeuroCartographer-generated notebooks.

This module is not a hardened sandbox for arbitrary untrusted notebooks. It is
only intended to catch syntax/runtime regressions in notebooks generated by this
package before stronger remote sandbox backends are added.
"""

from __future__ import annotations

import ast
import json
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from neurocartographer.models import NotebookExecutionReport

_BLOCKED_IMPORTS = {"os", "subprocess", "socket", "shutil", "pathlib", "requests", "urllib", "http", "ftplib", "multiprocessing"}
_BLOCKED_CALLS = {"open", "exec", "eval", "compile", "__import__", "input"}


def execute_notebook(notebook_path: Path, report_path: Path, timeout_seconds: int = 15) -> NotebookExecutionReport:
    notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
    code_cells = [cell for cell in notebook.get("cells", []) if cell.get("cell_type") == "code"]
    code = "\n\n".join(_cell_source(cell) for cell in code_cells).strip()
    blocked_reason = _safety_block_reason(code)
    if blocked_reason:
        report = NotebookExecutionReport(
            status="blocked",
            backend="restricted-local-subprocess",
            executed_cell_count=0,
            reason=blocked_reason,
        )
        _write_report(report_path, report)
        return report
    started = time.perf_counter()
    with tempfile.TemporaryDirectory(prefix="neurocartographer-notebook-") as tmp:
        script_path = Path(tmp) / "notebook_cells.py"
        script_path.write_text(code + "\n", encoding="utf-8")
        try:
            completed = subprocess.run(
                [sys.executable, str(script_path)],
                cwd=tmp,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=timeout_seconds,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            elapsed = time.perf_counter() - started
            report = NotebookExecutionReport(
                status="timed_out",
                backend="restricted-local-subprocess",
                executed_cell_count=len(code_cells),
                stdout=_decode_timeout_stream(exc.stdout),
                stderr=_decode_timeout_stream(exc.stderr),
                reason=f"timeout_seconds={timeout_seconds}",
                elapsed_seconds=round(elapsed, 4),
            )
            _write_report(report_path, report)
            return report
    elapsed = time.perf_counter() - started
    report = NotebookExecutionReport(
        status="passed" if completed.returncode == 0 else "failed",
        backend="restricted-local-subprocess",
        executed_cell_count=len(code_cells),
        stdout=completed.stdout,
        stderr=completed.stderr,
        reason="" if completed.returncode == 0 else f"exit_code={completed.returncode}",
        elapsed_seconds=round(elapsed, 4),
    )
    _write_report(report_path, report)
    return report


def _cell_source(cell: dict[str, object]) -> str:
    source = cell.get("source", "")
    if isinstance(source, list):
        return "".join(str(part) for part in source)
    return str(source)


def _safety_block_reason(code: str) -> str:
    if not code:
        return "notebook contains no code cells"
    try:
        tree = ast.parse(code)
    except SyntaxError as exc:
        return f"syntax error before execution: {exc}"
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".", 1)[0]
                if root in _BLOCKED_IMPORTS:
                    return f"blocked import: {root}"
        elif isinstance(node, ast.ImportFrom):
            root = (node.module or "").split(".", 1)[0]
            if root in _BLOCKED_IMPORTS:
                return f"blocked import: {root}"
        elif isinstance(node, ast.Call):
            name = _call_name(node.func)
            if name in _BLOCKED_CALLS:
                return f"blocked call: {name}"
    return ""


def _call_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return ""


def _decode_timeout_stream(value: bytes | str | None) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", "replace")
    return value


def _write_report(path: Path, report: NotebookExecutionReport) -> None:
    payload = {
        "status": report.status,
        "backend": report.backend,
        "executed_cell_count": report.executed_cell_count,
        "stdout": report.stdout,
        "stderr": report.stderr,
        "reason": report.reason,
        "elapsed_seconds": report.elapsed_seconds,
        "security_boundary": "restricted local subprocess for generated notebooks; not a hardened untrusted-code sandbox",
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
